---

- hosts: all
  become: true
  tasks:

  - name: install apache and php package

    package:
      update_cache: yes
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

