---

- hosts: all
  become: true

  pre_tasks:

  - name: Update servers
    apt:
      upgrade: dist
      update_cache: yes

  tasks:

  - name: Set time-zone to EST
    community.general.timezone:
      name: America/New_York

  - name: Install qemu-guest-agent
    apt:
      name:
        - qemu-guest-agent
      state: latest
      update_cache: yes

  - name: Create pihole group
    group:
      name: pihole
      state: present
    tags:
      - pihole

  - name: Create pihole user
    user:
      name: pihole
      group: pihole
      create_home: false
      shell: /usr/sbin/nologin
      state: present
    tags:
      - pihole

  - name: Create /etc/pihole directory
    file:
      path: /etc/pihole
      state: directory
      owner: pihole
      group: pihole
      mode: '0775'
    tags:
      - pihole

  - name: Create /etc/dnsmasq.d directory
    file:
      path: /etc/dnsmasq.d
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Check if /etc/pihole/setupVars.conf already exists
    stat:
      path: /etc/pihole/setupVars.conf
    register: setupvars

  - name: Create setupVars.conf
    copy:
      src: ./pihole/setupVars.conf
      dest: /etc/pihole/setupVars.conf
      owner: root
      group: root
      mode: '0644'
    when: setupvars.stat.exists == false

  - name: Check if pihole already installed
    stat:
      path: /usr/local/bin/pihole
    register: pihole_installed

  - name: Install pihole
    shell: 'curl -L https://install.pi-hole.net | bash /dev/stdin --unattended'
    when: pihole_installed.stat.exists == false

  - name: Install Unbound
    apt:
      name:
        - unbound
      state: latest

  - name: Check to see if /etc/unbound/unbound.conf.d/pi-hole.conf exists
    stat:
      path: /etc/unbound/unbound.conf.d/pi-hole.conf
    register: unbound_config

  - name: Create /etc/unbound/unbound.conf.d/pi-hole.conf
    copy:
      src: ./pihole/unbound.conf
      dest: /etc/unbound/unbound.conf.d/pi-hole.conf
      owner: root
      group: root
      mode: '0644'
    when: unbound_config.stat.exists == false

  - name: Restart unbound
    service:
      name: unbound
      state: restarted
      enabled: yes
