---

- hosts: all
  become: true

  pre_tasks:

  - name: update servers
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

  tasks:

  - name: set time-zone to EST
    community.general.timezone:
      name: America/New_York

  - name: install qemu-guest-agent
    apt:
      name:
        - qemu-guest-agent
      state: latest
      update_cache: yes
