---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and libapache2-mod-php
    tags: apache,debian
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: copy default html file for site
    tags: apache,debian
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: mariadb,db,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"
